[package]
name = "bug_game"
version = "0.1.0"
authors = ["mramirez <ramirezmike2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "94c4184" }
bevy_mod_raycast = { git = "https://github.com/aevyrie/bevy_mod_raycast", rev = "68626b7" }
bevy_mod_picking = { git = "https://github.com/aevyrie/bevy_mod_picking", rev = "30a9124" }
bevy_rapier3d = { git = "https://github.com/alec-deason/bevy_rapier", rev = "9bbfb4f" }

