[package]
name = "bug_game"
version = "0.1.0"
authors = ["mramirez <ramirezmike2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
bevy_mod_raycast = { git = "https://github.com/aevyrie/bevy_mod_raycast", rev = "68626b7" }
bevy_mod_picking = { git = "https://github.com/aevyrie/bevy_mod_picking", rev = "30a9124" }
bevy_rapier3d = { git = "https://github.com/alec-deason/bevy_rapier", rev = "9bbfb4f" }
petgraph = "0.5.1"
bevy_prototype_debug_lines = "0.2.2"
rand = "0.8"
serde = {version = "1", features = ["derive"]}
anyhow = "1.0"
ron = "0.6.2"
bevy_mod_debugdump = { git = "https://github.com/jakobhellermann/bevy_mod_debugdump" }
